[package]
name = "keyboard"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.14.0"
rand = { version = "0.9.0", features = ["std_rng"] }
rusqlite = "0.34.0"
tokio = { version = "1.43.0", features = ["full"] }
